import { StyleSheet } from "react-native"
import { color, font } from "../../ui/theme"

export const styles = StyleSheet.create({
  // Two-column layout
  menuLayout: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
    maxWidth: 780,
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  menuLeft: {
    flexDirection: "row",
    gap: 10,
    flex: 0.72,
    justifyContent: "center",
  },
  menuRight: {
    flex: 0.28,
    minWidth: 140,
  },

  // Online warriors panel (right column)
  onlineHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  onlineLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#7BED9F",
    shadowColor: "#7BED9F",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
  onlineHeaderText: {
    color: "rgba(232,197,71,0.6)",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 2,
  },
  emptyOnline: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
    backgroundColor: "rgba(232,197,71,0.02)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.06)",
    borderStyle: "dashed",
    gap: 6,
  },
  emptyOnlineText: {
    color: "rgba(232,197,71,0.4)",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1,
    textAlign: "center",
  },
  onlineListScroll: {
    maxHeight: 220,
  },
  onlineListContent: {
    gap: 4,
  },
  onlineCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(232,197,71,0.04)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.1)",
  },
  onlineCardAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(232,197,71,0.08)",
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  onlineCardName: {
    flex: 1,
    color: "rgba(255,255,255,0.7)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  onlineCardCode: {
    color: "#E8C547",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  // Action bar
  actionBar: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
    maxWidth: 480,
    marginTop: 4,
    marginBottom: 12,
  },
  hostBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(232,197,71,0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(232,197,71,0.3)",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#E8C547",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  hostBtnIcon: {
    fontSize: 22,
  },
  hostBtnTextWrap: {
    flex: 1,
  },
  hostBtnLabel: {
    color: "#E8C547",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 3,
  },
  hostBtnHint: {
    color: "rgba(232,197,71,0.45)",
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 0.5,
    marginTop: 1,
  },
  joinSection: {
    flex: 1,
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
  },
  joinInput: {
    flex: 1,
    backgroundColor: "rgba(232,197,71,0.04)",
    borderWidth: 1.5,
    borderColor: "rgba(232,197,71,0.2)",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    color: "#E8C547",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 4,
    textAlign: "center",
  },
  joinBtnNew: {
    backgroundColor: "#E8C547",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: "#E8C547",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  joinBtnNewDisabled: {
    opacity: 0.3,
    shadowOpacity: 0,
  },
  joinBtnNewText: {
    color: "#1a1a1a",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 2,
  },

  // Section divider
  sectionDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    width: "100%",
    maxWidth: 480,
  },
  sectionDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(232,197,71,0.1)",
  },
  sectionDividerText: {
    color: "rgba(232,197,71,0.4)",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 3,
  },

  // Online section — main attraction
  onlineSectionWrap: {
    width: "100%",
    maxWidth: 480,
    flex: 1,
    marginBottom: 12,
  },

  emptyOnlineSubtext: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.5,
  },

  onlineCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },

  onlineCardInfo: {
    flex: 1,
  },

  onlineCardStatus: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 0.5,
    marginTop: 2,
  },
  onlineCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  onlineCardCodeLabel: {
    color: "rgba(232,197,71,0.4)",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 2,
  },
  onlineCardCodeValue: {
    color: "#E8C547",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 1,
    marginTop: 1,
  },
  onlineCardArrow: {
    color: "rgba(232,197,71,0.4)",
    fontSize: 16,
    fontWeight: "900",
  },
  container: {
    flex: 1,
    backgroundColor: "#0B1410",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },

  // Background
  bgLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bgGlow: {
    position: "absolute",
    top: "15%",
    left: "30%",
    width: "40%",
    height: "55%",
    borderRadius: 250,
    backgroundColor: "rgba(232,197,71,0.04)",
  },
  bgRune: {
    position: "absolute",
    fontSize: 22,
    color: "rgba(232,197,71,0.04)",
  },
  bgHLine: {
    position: "absolute",
    top: "52%",
    left: 20,
    right: 20,
    height: 1,
    backgroundColor: "rgba(232,197,71,0.03)",
  },

  innerContent: { alignItems: "center", width: "100%" },

  // Header
  headerWrap: { alignItems: "center", marginBottom: 16 },
  headerOrnRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  headerLine: {
    width: 40,
    height: 1,
    backgroundColor: "rgba(232,197,71,0.2)",
  },
  headerDiamond: {
    color: "rgba(232,197,71,0.4)",
    fontSize: 8,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  title: {
    fontFamily: font.display,
    color: "#E8C547",
    fontSize: 28,
    letterSpacing: 3,
    textShadowColor: "rgba(232,197,71,0.3)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
  subtitle: {
    color: "rgba(232,197,71,0.35)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 3,
    marginTop: 4,
  },

  // Error
  errorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,75,75,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,75,75,0.25)",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginBottom: 12,
  },
  errorText: { color: "#FF6B6B", fontSize: 11, fontWeight: "700" },

  // Menu cards
  menuRow: { flexDirection: "row", gap: 18 },
  menuCard: {
    backgroundColor: "rgba(232,197,71,0.04)",
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.15)",
    borderRadius: 12,
    padding: 12, // was 16
    alignItems: "center",
    width: 160, // was 200
    gap: 4, // was 6
    overflow: "hidden",
  },
  menuCardGlow: {
    position: "absolute",
    top: -40,
    left: -40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(232,197,71,0.05)",
  },
  menuCardIconWrap: {
    width: 44, // was 54
    height: 44, // was 54
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "rgba(232,197,71,0.3)",
    backgroundColor: "rgba(232,197,71,0.05)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 2, // was 4
  },
  menuCardTitle: {
    fontFamily: font.heading,
    color: "#E8C547",
    fontSize: 13, // was 14
    letterSpacing: 2,
  },
  menuCardDesc: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 8, // was 9
    textAlign: "center",
    letterSpacing: 0.5,
    minHeight: 20, // was 22
  },
  // Unified card CTA — both menu cards end in the same gold action button,
  // pinned to the card's bottom edge so the equal-height pair reads balanced.
  cardActionBtn: {
    width: "100%",
    backgroundColor: color.gold,
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: color.gold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  cardActionDisabled: { opacity: 0.3, shadowOpacity: 0 },
  cardActionText: {
    fontFamily: font.heading,
    color: color.ink,
    fontSize: 11,
    letterSpacing: 2,
  },

  // Join code input — pinned toward the card bottom so the input + JOIN button
  // group aligns with the Host card's CREATE button across the equal-height pair.
  codeInputWrap: {
    marginTop: "auto",
    width: 120,
  },
  codeInput: {
    backgroundColor: "rgba(232,197,71,0.06)",
    borderWidth: 1.5,
    borderColor: "rgba(232,197,71,0.25)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: "#E8C547",
    fontSize: 18, // was 22
    fontWeight: "900",
    letterSpacing: 8, // was 10
    textAlign: "center",
  },
  // LOBBY
  lobbyHeaderWrap: {
    alignItems: "center",
    marginBottom: 12,
  },
  lobbyTitle: {
    fontFamily: font.display,
    color: "#E8C547",
    fontSize: 20,
    letterSpacing: 3,
    textShadowColor: "rgba(232,197,71,0.3)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },

  // Code box
  codeBox: {
    alignItems: "center",
    backgroundColor: "rgba(232,197,71,0.04)",
    borderRadius: 14,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: "rgba(232,197,71,0.25)",
    width: "100%",
  },
  codeLabel: {
    color: "rgba(232,197,71,0.5)",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 4,
  },
  codeDisplay: {
    flexDirection: "row",
    gap: 6,
    marginTop: 6,
    marginBottom: 4,
  },
  codeDigitBox: {
    width: 36,
    height: 46,
    borderRadius: 6,
    backgroundColor: "rgba(232,197,71,0.08)",
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  codeDigit: {
    color: "#E8C547",
    fontSize: 28,
    fontWeight: "900",
  },
  codeHint: {
    color: "rgba(255,255,255,0.25)",
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 1,
  },

  // Players section
  playersSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(232,197,71,0.1)",
  },
  playersTitle: {
    color: "rgba(232,197,71,0.5)",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 3,
  },
  playersList: { gap: 4 },
  playerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(232,197,71,0.03)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.06)",
  },
  playerRowHost: {
    backgroundColor: "rgba(232,197,71,0.05)",
    borderColor: "rgba(232,197,71,0.2)",
  },
  playerRowYou: {
    borderColor: "rgba(232,197,71,0.35)",
  },
  playerRowEmpty: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.04)",
    borderStyle: "dashed",
  },
  playerAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(232,197,71,0.08)",
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  playerAvatarHost: {
    borderColor: "#E8C547",
    backgroundColor: "rgba(232,197,71,0.15)",
  },
  playerAvatarEmpty: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.1)",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
  },
  playerName: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
    letterSpacing: 1,
  },
  playerNameYou: { color: "#E8C547" },
  emptySlotText: {
    color: "rgba(255,255,255,0.2)",
    fontSize: 11,
    fontStyle: "italic",
    flex: 1,
  },
  hostBadge: {
    backgroundColor: "rgba(232,197,71,0.15)",
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  hostBadgeText: {
    color: "#E8C547",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1,
  },
  youBadge: {
    backgroundColor: color.parchment,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  youBadgeText: {
    color: color.ink,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1,
  },

  // Actions — primary uses the shared GoldButton (engraved pinstripe, Cinzel
  // label) so the lobby's start matches Home's and Lounge's CTA craft.
  lobbyPrimary: { width: "100%" },

  waitingBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: "rgba(232,197,71,0.03)",
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.08)",
  },
  waitingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#7BED9F",
  },
  waitingText: {
    color: "rgba(232,197,71,0.5)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },

  leaveBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,100,100,0.2)",
    backgroundColor: "rgba(255,100,100,0.04)",
  },
  leaveBtnText: {
    color: "rgba(255,100,100,0.6)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },

  backBtn: {
    marginTop: 18,
    paddingVertical: 8,
    paddingHorizontal: 24,
  },
  backText: {
    color: "#E8C547",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },

  lobbyContent: {
    alignItems: "center",
    width: "100%",
    maxWidth: 600,
  },
  lobbyBody: {
    flexDirection: "row",
    width: "100%",
    gap: 16,
    marginTop: 12,
  },
  // Top-aligned, not centred — the code box should sit level with the players
  // header in the right column rather than floating to the vertical middle.
  lobbyLeft: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 16,
  },
  lobbyRight: {
    flex: 1,
  },
  playersScroll: {
    maxHeight: 200,
  },
  lobbyActions: {
    alignItems: "center",
    gap: 8,
    width: "100%",
  },
  onlineSection: {
    width: "100%",
    maxWidth: 420,
    marginTop: 16,
    alignItems: "center",
  },
  onlineHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
    width: "100%",
  },
  onlineHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(232,197,71,0.12)",
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#7BED9F",
  },
  onlineTitle: {
    color: "rgba(232,197,71,0.5)",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 3,
  },
  onlineScroll: {
    maxHeight: 140,
    width: "100%",
  },
  onlineList: {
    gap: 4,
    paddingHorizontal: 4,
  },
  onlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(232,197,71,0.03)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.08)",
  },
  onlineAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(232,197,71,0.08)",
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  onlineAvatarText: {
    fontSize: 10,
    color: "rgba(232,197,71,0.6)",
  },
  onlineName: {
    flex: 1,
    color: "rgba(255,255,255,0.65)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  onlineCodeBadge: {
    backgroundColor: "rgba(232,197,71,0.08)",
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.15)",
  },
  onlineCodeText: {
    color: "#E8C547",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  inviteSection: { marginTop: 10 },
  inviteScroll: { maxHeight: 100 },
  inviteEmptyText: {
    color: "rgba(255,255,255,0.25)",
    fontSize: 9,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 8,
  },
  inviteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(232,197,71,0.03)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "rgba(232,197,71,0.08)",
  },
  inviteName: {
    flex: 1,
    color: "rgba(255,255,255,0.7)",
    fontSize: 11,
    fontWeight: "700",
  },
  inviteBtn: {
    backgroundColor: "#E8C547",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  inviteBtnSent: {
    backgroundColor: "rgba(232,197,71,0.12)",
  },
  inviteBtnText: {
    color: "#1a1a1a",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1,
  },
  inviteBtnTextSent: {
    color: "rgba(232,197,71,0.6)",
  },
  inviteModalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  inviteModalCard: {
    backgroundColor: "#14100C",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(232,197,71,0.4)",
    paddingHorizontal: 28,
    paddingVertical: 20,
    alignItems: "center",
    gap: 6,
    maxWidth: 320,
  },
  inviteModalTitle: {
    fontFamily: font.heading,
    color: "#E8C547",
    fontSize: 14,
    letterSpacing: 3,
  },
  inviteModalText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 12,
    textAlign: "center",
  },
  inviteModalCode: {
    backgroundColor: "rgba(232,197,71,0.1)",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginVertical: 4,
  },
  inviteModalCodeText: {
    color: "#E8C547",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 2,
  },
  inviteModalBtns: { flexDirection: "row", gap: 10, marginTop: 4 },
  inviteAcceptBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#E8C547",
    borderRadius: 10,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  inviteAcceptText: {
    fontFamily: font.heading,
    color: "#1a1a1a",
    fontSize: 13,
    letterSpacing: 1,
  },
  inviteDeclineBtn: {
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255,100,100,0.3)",
  },
  inviteDeclineText: {
    color: "rgba(255,100,100,0.6)",
    fontSize: 12,
    fontWeight: "700",
  },
})
